export const INCREMENT_QUESTION_INDEX = 'INCREMENT_QUESTION_INDEX';
export type INCREMENT_QUESTION_INDEX = typeof INCREMENT_QUESTION_INDEX;

export const ADD_POINTS = 'ADD_POINTS';
export type ADD_POINTS = typeof ADD_POINTS;